-- AlterTable
ALTER TABLE `dialog` ADD COLUMN `status` ENUM('TYPING', 'ONLINE', 'OFFLINE') NOT NULL DEFAULT 'OFFLINE';

-- AlterTable
ALTER TABLE `user` ADD COLUMN `status` ENUM('ONLINE', 'OFFLINE') NOT NULL DEFAULT 'OFFLINE';
