export const PRISMA_SELECT = {
  USER: {
    id: true,
    email: true,
    isVerified: true,
    bio: true,
    createdAt: true,
    lastname: true,
    name: true,
    updatedAt: true,
    username: true,
    status: true,
  },
  MESSAGE: {
    id: true,
    message: true,
    read: true,
    replyMessage: {
      select: {
        id: true,
        message: true,
        read: true,
        replyMessageId: true,
        user: true,
        userId: true,
        createdAt: true,
        updatedAt: true,
      },
    },
    replyMessageId: true,
    user: true,
    userId: true,
    createdAt: true,
    updatedAt: true,
  },
};
